#!/bin/sh

#  ____                _
# | __ )  ___  ___ ___| | _____ _   _
# |  _ \ / _ \/ __/ __| |/ / _ \ | | |
# | |_) | (_) \__ \__ \   <  __/ |_| |
# |____/ \___/|___/___/_|\_\___|\__, |
#                               |___/ v1.1
# GitHub: https://github.com/SpyHoodle/bosskey


function undo() {
  # Unmute the volume
  pamixer --unmute

  # Refresh the status bar
  kill -35 $(pidof dwmblocks)
}

while getopts "lu" options; do
  case $options in
    l)
      # Mute the volume
      pamixer --mute

      # Pause any playing media
      playerctl pause

      # Lock the screen using slock(1)
      slock
      ;;

    u)
      # Once unlocked, only unmute the volume
      undo
      ;;
  esac
done
